### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by D4nte**
Attempt to add a new language. It actually does not seem to work as the "/es/" in the url path is lost when navigating.

@jakubgs Do you have any other idea? https://github.com/rust-lang/mdBook/issues/5 provides idea on how it could be implemented in mdbook but not really any work around.

It may be better/easier to just go with Docusauraus which has native multinlingual support: https://docusaurus.io/docs/i18n/introduction.

@jakubgs Are you familiar with Docusaurus? Are you able to set it up?

### CODE REVIEW

**Comment by jakubgs** [comment]
>Do you have any other idea?

Not really.

>Are you familiar with Docusaurus?

Nope.

>Are you able to set it up?

Yes.

**Comment by D4nte** [comment]
As discussed in Discord, let's go with readthedocs please. Lighter than docusaurus and has the translation features we need.

**Comment by D4nte** [comment]
@jakubgs is looking into readthedocs

**Comment by jakubgs** [comment]
Researching in: https://github.com/vacp2p/docs.dappconnect.dev/issues/7

**Pull request closed without merging**
