### PR TITLE
replace mdBook with Hugo for site generation

### PR DESCRIPTION
**Pull request by jakubgs**
An attempt to get multi-language support with a simple site generator: https://gohugo.io/

Research issue: https://github.com/vacp2p/docs.dappconnect.dev/issues/7
Theme: https://themes.gohugo.io/themes/hugo-book/

I've dropped the Waku specs part for simplicity of the PR, you can re-add it later yourself @D4nte .

### CODE REVIEW

**Comment by jakubgs** [comment]
With some manual adjustment to the CI Job I deployed this version to https://dev-docs.dappconnect.dev/.

**Review by D4nte — COMMENTED** [review]
- Links to other md files are now broken, can this be fixed?
- Could you update the README to serve locally? I guess it's just `git submodule init && git submodule update && hugo server` ?

It looks awesome and the multi-lang support is great too. thanks for that.

**Review by D4nte — APPROVED** [review]

**Comment by jakubgs** [comment]
Fixed links and added instructions to run `git submodule update --init`.

**Comment by jakubgs** [comment]
Merged into `develop` and `master` rebased on `develop`. Both branches deployed.

**Pull request merged**
